apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend
  name: backend
spec:
  selector:
    service: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
