apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    service: nginx-logs
  name: nginx-logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
status: {}
