apiVersion: v1
kind: Service
metadata:
  labels:
    service: nginx
  name: nginx
spec:
  selector:
    service: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 80
  type: LoadBalancer
status:
  loadBalancer: {}
